CC32 := i686-w64-mingw32-gcc
CC64 := x86_64-w64-mingw32-gcc
EXTRA_CFLAGS ?=

# Midnight-Hail: seed-regen happens up front so BOTH generator rebuilds AND
# the baked loader_exe_x64.h see the same rotation constants.

donut: clean seed
	$(info ###### RELEASE ######)
	gcc -I include loader/exe2h/exe2h.c -oexe2h
	$(CC64) -I include loader/exe2h/exe2h.c loader/exe2h/mmap-windows.c -lshlwapi -oexe2h.exe

	$(CC32) $(EXTRA_CFLAGS) -DBYPASS_AMSI_B -DBYPASS_WLDP_A -DBYPASS_ETW_B -fno-toplevel-reorder -fpack-struct=8 -fPIC -O0 -nostdlib loader/loader.c loader/depack.c loader/clib.c hash.c encrypt.c -I include -oloader.exe
	@python3 tools/nop-permute.py loader.exe
	./exe2h loader.exe

	$(CC64) $(EXTRA_CFLAGS) -DBYPASS_AMSI_B -DBYPASS_WLDP_A -DBYPASS_ETW_B -fno-toplevel-reorder -fpack-struct=8 -fPIC -O0 -nostdlib loader/loader.c loader/depack.c loader/clib.c hash.c encrypt.c -I include -oloader.exe
	@python3 tools/nop-permute.py loader.exe
	./exe2h loader.exe

	$(CC64) $(EXTRA_CFLAGS) -Wall -fpack-struct=8 -DDONUT_EXE -I include donut.c hash.c encrypt.c format.c loader/clib.c lib/aplib64.lib -odonut.exe

seed:
	@python3 tools/seed-gen.py

debug: clean seed
	$(info ###### DEBUG ######)
	$(CC32) $(EXTRA_CFLAGS) -DCLIB -DBYPASS_AMSI_B -DBYPASS_WLDP_A -DBYPASS_ETW_B -Wno-format -fpack-struct=8 -DDEBUG -I include loader/loader.c hash.c encrypt.c loader/depack.c loader/clib.c -oloader32.exe -lole32 -lshlwapi
	$(CC64) $(EXTRA_CFLAGS) -DCLIB -DBYPASS_AMSI_B -DBYPASS_WLDP_A -DBYPASS_ETW_B -Wno-format -fpack-struct=8 -DDEBUG -I include loader/loader.c hash.c encrypt.c loader/depack.c loader/clib.c -oloader64.exe -lole32 -lshlwapi

clean:
	rm -f exe2h exe2h.exe loader.bin instance donut.o hash.o encrypt.o format.o clib.o hash encrypt donut hash.exe encrypt.exe donut.exe lib/libdonut.a lib/libdonut.so loader.exe loader32.exe loader64.exe

.PHONY: seed clean
